// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz9O_F_8EGlabE091HrxvqL5LdgLVKavc',
    appId: '1:708019773115:web:c041373b8e55b7bed9539e',
    messagingSenderId: '708019773115',
    projectId: 'draft-b73b0',
    authDomain: 'draft-b73b0.firebaseapp.com',
    databaseURL: 'https://draft-b73b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'draft-b73b0.appspot.com',
    measurementId: 'G-4VWQBS885C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO83g73CpYG0eUvoHGJ-53zxz7nA7eJ1Q',
    appId: '1:708019773115:android:a815802f12369c3bd9539e',
    messagingSenderId: '708019773115',
    projectId: 'draft-b73b0',
    databaseURL: 'https://draft-b73b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'draft-b73b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMJSS8TvxBzxX18Oxix0H1rPM1Uge0k5E',
    appId: '1:708019773115:ios:59a3d97544df270dd9539e',
    messagingSenderId: '708019773115',
    projectId: 'draft-b73b0',
    databaseURL: 'https://draft-b73b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'draft-b73b0.appspot.com',
    iosBundleId: 'com.example.finalMae3rdWh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMJSS8TvxBzxX18Oxix0H1rPM1Uge0k5E',
    appId: '1:708019773115:ios:8ae0bc173742b1a8d9539e',
    messagingSenderId: '708019773115',
    projectId: 'draft-b73b0',
    databaseURL: 'https://draft-b73b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'draft-b73b0.appspot.com',
    iosBundleId: 'com.example.finalMae3rdWh.RunnerTests',
  );
}
